name: Build App

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cancel-previous:
    name: Cancel Stale In-progress Builds
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  static:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Static Analysis
        run: ./gradlew assemble check -x test --continue --stacktrace --parallel
      - name: Archive ktlint results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ktlint-results
          path: "**/build/reports/ktlint/"
      - name: Archive lint results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: "**/build/reports/lint-results.*"

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Fix Gradlew
        run: --chmod=+x gradlew
      - name: Run Unit Tests
        run: ./gradlew test jacocoTestReport --continue --stacktrace --parallel
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
      - name: Archive Unit Test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-results
          path: "**/build/reports/tests/"

